version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Backend/dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Frontend/dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"